name: "PR Triage"
on:
  pull_request_target:
    types: [opened, reopened, ready_for_review, locked]

permissions:
  pull-requests: write

jobs:
  # https://github.com/marketplace/actions/auto-author-assign
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - name: "Assign Author to PR"
        uses: toshimaru/auto-author-assign@v1.3.5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  # https://github.com/shufo/auto-assign-reviewer-by-files
  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Request review based on files changes and/or groups the author belongs to
        uses: shufo/auto-assign-reviewer-by-files@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config: .github/reviewers.yml
