name: Mergifyio backport

on: [issue_comment]

permissions:
  pull-requests: write
  contents: read

jobs:
  mergifyio-backport:
    uses: vyos/.github/.github/workflows/label-backport.yml@equuleus
    secrets: inherit
